uses "curl","console","string";

object crl;
string content, headers;

crl = new Curl.Curl();
Console.println( "Curl Object: "+ crl );
Console.println( "Set URL: "+ crl.setOption(Curl.CURLOPT_URL,"http://www.example.com") );
Console.println( "Set Get Headers: "+ crl.setOption(Curl.CURLOPT_HEADER, 1) );
Console.println( "Set Return Data: "+ crl.setOption(Curl.CURLOPT_RETURNTRANSFER, 1) );
Console.println( "Exec: "+ crl.exec() );
headers = crl.getHeaders();
content = crl.getContent();
Console.println( "Headers Length: "+ String.length(headers) );
Console.println( "Content Length: "+ String.length(content) );
Console.println( "Headers: "+ headers);
Console.println( "Content: "+ content);
Console.println("****************************************************************\n\n");

crl = new Curl.Curl();
Console.println( "Curl Object: "+ crl );
Console.println( "Set URL: "+ crl.setOption(Curl.CURLOPT_URL,"http://www.example.com") );
Console.println( "Set Get Headers: "+ crl.setOption(Curl.CURLOPT_HEADER, 1) );
Console.println( "Set No Body: "+ crl.setOption(Curl.CURLOPT_NOBODY, 1) );
Console.println( "Set Return Data: "+ crl.setOption(Curl.CURLOPT_RETURNTRANSFER, 1) );
Console.println( "Exec: "+ crl.exec());
headers = crl.getHeaders();
content = crl.getContent();
Console.println( "Headers Length: "+ String.length(headers) );
Console.println( "Content Length: "+ String.length(content) );
Console.println( "Headers: "+ headers);
Console.println( "Content: "+ content);

